import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

import type { role_company_media_type, role_company_type, subscription_status, contract_status, product_selection, pricing_type, plan_type, duration_type, address_type, cart_type, coupon_duration_type, invoice_item_type, order_line_type, plan_status, payout_status, order_status, recurring_type, purchase_type } from "./enums";

export type address = {
    id: Generated<string>;
    user_id: string;
    first_name: string | null;
    last_name: string | null;
    phone_country_code: Generated<string | null>;
    phone_number: string | null;
    address_line_1: string | null;
    address_line_2: string | null;
    state: string | null;
    county: string | null;
    city: string | null;
    postal_code: string | null;
    country: Generated<string>;
    is_default: Generated<boolean>;
    type: address_type | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type address_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type availability = {
    company_id: string;
    user_id: string;
};
export type cart = {
    id: Generated<number>;
    user_id: string;
    type: Generated<cart_type>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type cart_line = {
    id: Generated<number>;
    cart_id: number;
    subscription_id: string;
    extra: unknown | null;
    actor: string | null;
    deleted: Generated<boolean>;
};
export type cart_line_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type cart_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type company = {
    id: Generated<string>;
    name: string;
    country: string | null;
    phone_country_code: string | null;
    phone_number: string | null;
    about_us: string | null;
    currency: string | null;
    vat: string | null;
    vat_percent: string | null;
    taly_percent: number | null;
    order_email: string | null;
    type: Generated<role_company_type | null>;
    foreign_ids: unknown | null;
    sync_settings: unknown | null;
    headquarter_country: string | null;
    website: string | null;
    industries: string | null;
    sell_type: string | null;
    slug: string | null;
    ecommerce_description: string | null;
    theme: unknown | null;
    onboarding: unknown | null;
    published: Generated<boolean>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type company_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type company_media = {
    id: Generated<string>;
    media: string;
    type: role_company_media_type | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
    company_id: string;
};
export type coupon = {
    id: Generated<number>;
    company_id: string;
    name: string;
    amount_off: number | null;
    percent_off: number | null;
    currency: string | null;
    duration: Generated<coupon_duration_type>;
    renew_duration: number | null;
    applies_to: unknown | null;
    active: Generated<boolean>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type coupon_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type invoice = {
    id: Generated<string>;
    user_id: string;
    status: string;
    payment_intent: string;
    total_amount: number;
    currency: string;
    address_id: string;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type invoice_item = {
    id: Generated<string>;
    invoice_id: string;
    description: string;
    quantity: number;
    price: number;
    subscription_id: string | null;
    company_id: string | null;
    type: Generated<invoice_item_type>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type invoice_item_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type invoice_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type order = {
    id: Generated<string>;
    user_id: string;
    currency: string;
    shipping_address: string;
    company_id: string;
    total_discount: number | null;
    total_price: number;
    status: Generated<order_status>;
    created_at: Generated<Timestamp>;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type order_line = {
    id: Generated<string>;
    description: string | null;
    part_of: string | null;
    order_id: string;
    product_variant_id: string | null;
    coupon: string | null;
    type: Generated<order_line_type>;
    quantity: number;
    line_price: number;
    line_discount: number | null;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type order_line_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type order_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type order_subscription = {
    id: Generated<string>;
    order_id: string;
    subscription_id: string;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type order_subscription_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type payment_method = {
    id: Generated<string>;
    user_id: string;
    payment_type: string | null;
    card_brand: string | null;
    card_last_four: string | null;
    exp_month: number | null;
    exp_year: number | null;
    payment_method_id: string | null;
    is_default: Generated<boolean>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type payment_method_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type payout = {
    id: Generated<string>;
    company_id: string;
    order_id: string;
    amount: number;
    currency: string;
    status: Generated<payout_status>;
    scheduled_date: Timestamp;
    payment_method_id: string | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type payout_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type plan = {
    id: Generated<string>;
    company_id: string;
    foreign_ids: unknown | null;
    title: string;
    slug: Generated<string>;
    description: string | null;
    delivery_details: string | null;
    terms: string | null;
    allow_delivery_preference: Generated<boolean>;
    price_at_origin: number | null;
    currency_at_origin: string | null;
    media_cover: unknown | null;
    recurring: unknown | null;
    duration_value: number | null;
    duration_type: duration_type | null;
    age_restricted: Generated<boolean>;
    voucher: Generated<boolean>;
    product_selection: Generated<product_selection>;
    pricing_type: Generated<pricing_type>;
    plan_type: Generated<plan_type>;
    category_id: string | null;
    recurrent_discount_percent: Generated<number>;
    allow_once_payment: Generated<boolean>;
    status: Generated<plan_status>;
    tag: unknown | null;
    user_sales_limit: number | null;
    total_sales_limit: number | null;
    total_sales: Generated<number>;
    sold_out: Generated<boolean>;
    created_at: Generated<Timestamp>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type plan_category = {
    id: Generated<string>;
    name: string;
    slug: string;
    icon: string;
    extra: unknown | null;
};
export type plan_feature = {
    id: Generated<string>;
    plan_id: string;
    feature: unknown;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type plan_feature_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type plan_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type plan_media = {
    id: Generated<string>;
    plan_id: string;
    media: string;
    foreign_ids: unknown | null;
    extra: unknown | null;
};
export type plan_price = {
    id: Generated<string>;
    plan_id: string;
    country: string;
    currency: string;
    amount: Generated<number>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type plan_price_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type plan_product_variant = {
    id: Generated<string>;
    plan_id: string;
    product_variant_id: string;
    quantity: Generated<number>;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type plan_product_variant_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type plan_product_variant_price = {
    id: Generated<string>;
    plan_product_variant_id: string;
    country: string;
    currency: string;
    amount: Generated<number>;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type plan_product_variant_price_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type product = {
    id: Generated<string>;
    company_id: string;
    name: string;
    description: string | null;
    brand: string | null;
    product_media_id: string | null;
    unit: string | null;
    unit_plural: string | null;
    breakdown: string | null;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type product_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type product_media = {
    id: Generated<string>;
    product_id: string | null;
    product_variant_id: string | null;
    media: unknown;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type product_sync = {
    company_id: string;
    foreign_id: string;
    object: unknown;
};
export type product_variant = {
    id: Generated<string>;
    product_id: string;
    name: string;
    description: string | null;
    description_long: string | null;
    sku: string | null;
    volume_or_weight: string | null;
    nutritional_facts: string | null;
    ingredients: string | null;
    allergens: string | null;
    age_restricted: Generated<boolean>;
    age: number | null;
    in_stock: Generated<boolean>;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type product_variant_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type product_variant_price = {
    id: Generated<string>;
    product_variant_id: string;
    country: string;
    currency: string;
    amount: Generated<number>;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type product_variant_price_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type shipping_zone = {
    id: Generated<string>;
    country: string;
    whole_country_delivery: Generated<boolean>;
    company_id: string;
    free_delivery: Generated<boolean>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type shipping_zone_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type shipping_zone_price = {
    id: Generated<string>;
    shipping_zone_id: string | null;
    shipping_zone_rule_id: string | null;
    currency: string;
    amount: string;
    delivery_threshold: Generated<number | null>;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type shipping_zone_price_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type shipping_zone_rule = {
    id: Generated<string>;
    shipping_zone_id: string;
    schema_version: string;
    is_delivery_related: Generated<boolean>;
    rule: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type shipping_zone_rule_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type subscription = {
    id: Generated<string>;
    created_at: Generated<Timestamp>;
    user_id: string | null;
    plan_id: string;
    status: Generated<subscription_status>;
    delivery_day: string | null;
    recurring: recurring_type | null;
    renew_at: Timestamp | null;
    cancelled_at: Timestamp | null;
    step: Generated<number>;
    contract_amount: number | null;
    contract_currency: string | null;
    contract_country: string | null;
    contract_status: Generated<contract_status>;
    contract_update_requested_at: Timestamp | null;
    contract_update_amount: number | null;
    address_id: string | null;
    payment_retry: Generated<number>;
    coupon_id: number | null;
    purchase_type: Generated<purchase_type>;
    foreign_ids: unknown | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type subscription_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type subscription_plan_product_variant = {
    id: Generated<string>;
    subscription_id: string;
    plan_product_variant_id: string;
    quantity: number;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type subscription_plan_product_variant_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type trial = {
    id: Generated<string>;
    plan_id: string;
    user_id: string;
    total: Generated<number>;
};
export type user = {
    id: Generated<string>;
    first_name: string;
    last_name: Generated<string>;
    email: string;
    email_verified_at: Timestamp | null;
    phone_country_code: Generated<string>;
    phone_number: string | null;
    gender: string | null;
    birthday: Timestamp | null;
    phone_verified_at: Timestamp | null;
    employer_id: string | null;
    job_role: string | null;
    policy_agreement: Generated<boolean>;
    marketing_consent: Generated<boolean>;
    foreign_ids: unknown | null;
    media_profile: string | null;
    extra: unknown | null;
    deleted: Generated<boolean>;
    actor: string | null;
};
export type user_log = {
    id: Generated<number>;
    record: unknown;
    action: string;
    actor: string | null;
    action_time: Timestamp;
};
export type DB = {
    address: address;
    address_log: address_log;
    availability: availability;
    cart: cart;
    cart_line: cart_line;
    cart_line_log: cart_line_log;
    cart_log: cart_log;
    company: company;
    company_log: company_log;
    company_media: company_media;
    coupon: coupon;
    coupon_log: coupon_log;
    invoice: invoice;
    invoice_item: invoice_item;
    invoice_item_log: invoice_item_log;
    invoice_log: invoice_log;
    order: order;
    order_line: order_line;
    order_line_log: order_line_log;
    order_log: order_log;
    order_subscription: order_subscription;
    order_subscription_log: order_subscription_log;
    payment_method: payment_method;
    payment_method_log: payment_method_log;
    payout: payout;
    payout_log: payout_log;
    plan: plan;
    plan_category: plan_category;
    plan_feature: plan_feature;
    plan_feature_log: plan_feature_log;
    plan_log: plan_log;
    plan_media: plan_media;
    plan_price: plan_price;
    plan_price_log: plan_price_log;
    plan_product_variant: plan_product_variant;
    plan_product_variant_log: plan_product_variant_log;
    plan_product_variant_price: plan_product_variant_price;
    plan_product_variant_price_log: plan_product_variant_price_log;
    product: product;
    product_log: product_log;
    product_media: product_media;
    product_sync: product_sync;
    product_variant: product_variant;
    product_variant_log: product_variant_log;
    product_variant_price: product_variant_price;
    product_variant_price_log: product_variant_price_log;
    shipping_zone: shipping_zone;
    shipping_zone_log: shipping_zone_log;
    shipping_zone_price: shipping_zone_price;
    shipping_zone_price_log: shipping_zone_price_log;
    shipping_zone_rule: shipping_zone_rule;
    shipping_zone_rule_log: shipping_zone_rule_log;
    subscription: subscription;
    subscription_log: subscription_log;
    subscription_plan_product_variant: subscription_plan_product_variant;
    subscription_plan_product_variant_log: subscription_plan_product_variant_log;
    trial: trial;
    user: user;
    user_log: user_log;
};
